<a href="https://colab.research.google.com/github/Py7949/Data-Science-/blob/main/Data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.Data Loading**

In [1]:
!git clone https://github.com/AshishJangra27/datasets

Cloning into 'datasets'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 328 (delta 19), reused 54 (delta 9), pack-reused 235 (from 1)
Receiving objects: 100% (328/328), 278.62 MiB | 16.96 MiB/s, done.
Resolving deltas: 100% (145/145), done.
Updating files: 100% (225/225), done.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/datasets/Airbnb/airbnb_v2.csv")
df

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...",...,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [6]:
df.head()

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm

In [ ]:
df.tail()

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
12800,12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...",...,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [ ]:
df.head(2)

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am

In [ ]:
df.columns

Index(['Unnamed: 0', 'id', 'name', 'rating', 'reviews', 'host_name', 'host_id',
       'address', 'features', 'amenities', 'safety_rules', 'hourse_rules',
       'img_links', 'price', 'country', 'bathrooms', 'beds', 'guests',
       'toiles', 'bedrooms', 'studios', 'checkin', 'checkout'],
      dtype='object')

In [ ]:
df['name']

0                                           Perla bungalov
1        Authentic Beach Architect Sheltered Villa with...
2                                        cottages sataplia
3                              Sapanca Breathable Bungalow
4                                            Bungalov Ev 2
                               ...
12800              Brown Dome House No. 3, full of healing
12801         Bubble Hotel Ubud with Bathtub under the Sky
12802                                     Paradise Eco Hub
12803       WisDOME - Mentigi Bay Village - Gilis - Lombok
12804     Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]
Name: name, Length: 12805, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12805 entries, 0 to 12804
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    12805 non-null  int64
 1   id            12805 non-null  int64
 2   name          12805 non-null  object
 3   rating        12805 non-null  object
 4   reviews       12805 non-null  object
 5   host_name     12797 non-null  object
 6   host_id       12805 non-null  float64
 7   address       12805 non-null  object
 8   features      12805 non-null  object
 9   amenities     12805 non-null  object
 10  safety_rules  12805 non-null  object
 11  hourse_rules  12805 non-null  object
 12  img_links     12805 non-null  object
 13  price         12805 non-null  int64
 14  country       12805 non-null  object
 15  bathrooms     12805 non-null  int64
 16  beds          12805 non-null  int64
 17  guests        12805 non-null  int64
 18  toiles        12805 non-null  int64
 19  bedrooms      12805 non-null  int64
 20  studios       12805 non-null  int64
 21  checkin       12005 non-null  object
 22  checkout      10355 non-null  object
dtypes: float64(1), int64(9), object(13)
memory usage: 2.2+ MB

In [ ]:
df.isnull().sum()

Unnamed: 0         0
id                 0
name               0
rating             0
reviews            0
host_name          8
host_id            0
address            0
features           0
amenities          0
safety_rules       0
hourse_rules       0
img_links          0
price              0
country            0
bathrooms          0
beds               0
guests             0
toiles             0
bedrooms           0
studios            0
checkin          800
checkout        2450
dtype: int64

In [11]:
#del df['Unnamed: 0']
del df['host_name']

In [12]:
df

,id,name,rating,reviews,host_id,address,features,amenities,safety_rules,hourse_rules,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,49849504,Perla bungalov,4.71,64,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,50699164,cottages sataplia,4.85,68,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,49871422,Sapanca Breathable Bungalow,5.0,13,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,51245886,Bungalov Ev 2,New,0,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12799,640474109823176234,"Holiday home, Plemmirio",New,0,385223440.0,"Syracuse, Sicilia, Italy","8 guests,4 bedrooms,4 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free on-stree...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 8:00 pm,Check out: 10:00 a...",...,20311,Italy,2,4,8,0,4,0,2 00 pm - 8 00 pm,10 00 am
12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 12:00 pm,No pets...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [18]:
df ['id'].nunique()

10355

In [19]:
len(df['id'].unique())

10355

In [20]:
len(df['id'])

10355

In [21]:
jobs = pd.read_csv('/content/datasets/Job Postings/jobs.csv.zip')
jobs

,job_id,job_role,company,experience,salary,location,rating,reviews,resposibilities,posted_on,job_link,company_link
0,7.012301e+10,Branch Banking - Calling For Women Candidates,Hdfc Bank,1-6 Yrs,Not disclosed,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...",4.0,39110 Reviews,"Customer Service,Sales,Relationship Management",1 Day Ago,https://www.naukri.com/job-listings-branch-ban...,https://www.naukri.com/hdfc-bank-jobs-careers-213
1,6.012391e+10,Product Owner Senior Manager,Accenture,11-15 Yrs,Not disclosed,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",4.1,32129 Reviews,"Product management,Market analysis,Change mana...",1 Day Ago,https://www.naukri.com/job-listings-product-ow...,https://www.naukri.com/accenture-jobs-careers-...
2,6.012391e+10,Employee Relations and Policies Associate Manager,Accenture,3-7 Yrs,Not disclosed,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",4.1,32129 Reviews,"Business process,Change management,Team manage...",1 Day Ago,https://www.naukri.com/job-listings-employee-r...,https://www.naukri.com/accenture-jobs-careers-...
3,6.012391e+10,Employee Relations and Policies Specialist,Accenture,3-7 Yrs,Not disclosed,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",4.1,32129 Reviews,"Business process,Change management,Team manage...",1 Day Ago,https://www.naukri.com/job-listings-employee-r...,https://www.naukri.com/accenture-jobs-careers-...
4,6.012301e+10,SAP BO Consultant,Mindtree,5-7 Yrs,Not disclosed,"Hybrid - Kolkata, Hyderabad/Secunderabad, Pune...",4.1,3759 Reviews,"SAP BO,PL / SQL,Oracle SQL,SAP Business Object...",1 Day Ago,https://www.naukri.com/job-listings-sap-bo-con...,https://www.naukri.com/mindtree-jobs-careers-3...
...,...,...,...,...,...,...,...,...,...,...,...,...
79142,6.012301e+10,.Net Fullstack Developer,Citiustech,3-8 Yrs,"7,00,000 - 17,00,000 PA.","Hybrid - Pune, Bangalore/Bengaluru, Mumbai (Al...",4.0,742 Reviews,"c#,.net core,javascript,Microservices,Angular,...",2 Days Ago,https://www.naukri.com/job-listings-net-fullst...,https://www.naukri.com/citiustech-jobs-careers...
79143,1.122201e+10,Senior (BI) Business Intelligence Architect,Hexaware Technologies,10-13 Yrs,Not disclosed,"Hybrid - Pune, Chennai, Bangalore/Bengaluru, M...",3.7,3172 Reviews,"Informatica Mdm,etl,business intelligence,Agil...",1 Day Ago,https://www.naukri.com/job-listings-senior-bi-...,https://www.naukri.com/hexaware-technologies-j...
79144,1.512220e+11,PowerBI Developer,EY,5-10 Yrs,Not disclosed,"Hybrid - Pune, Mumbai (All Areas)",3.8,6267 Reviews,"pagination,Power Bi,Dax",2 Days Ago,https://www.naukri.com/job-listings-powerbi-de...,https://www.naukri.com/ey-jobs-careers-9156
79145,2.712220e+11,Customer Service Associate,Tech Mahindra,0-2 Yrs,"2,50,000 - 3,50,000 PA.","Temp. WFH - Noida, Kolkata, New Delhi, Hyderab...",3.7,21440 Reviews,"Bengali,International BPO,BPO,Customer Service...",10 Days Ago,https://www.naukri.com/job-listings-customer-s...,https://www.naukri.com/tech-mahindra-jobs-care...
79146,2.112220e+11,Senior Java BED ( PAN India)- KG,Tech Mahindra,8-12 Yrs,"25,00,000 - 27,50,000 PA.","Temp. WFH - Noida, Kolkata, Hyderabad/Secunder...",3.7,21440 Reviews,"Kafka,sql,spring boot,REST API,java,Lambda,Des...",3 Days Ago,https://www.naukri.com/job-listings-senior-jav...,https://www.naukri.com/born-commerce-jobs-care...

In [24]:
jobs['salary'].value_counts()

salary
Not disclosed                                          45544
6,50,000 - 9,00,000 PA.                                 3330
6,00,000 - 8,00,000 PA.                                 1114
5,00,000 - 10,00,000 PA.                                1087
2,50,000 - 3,50,000 PA.                                  599
                                                       ...
4,00,000 - 9,00,000 PA. (Including Variable: 20.0%)        1
4,00,00,000 - 4,50,00,000 PA.                              1
2,00,000 - 6,00,000 PA. (Including Variable: 30.0%)        1
60,00,000 - 1,00,00,000 PA.                                1
75,00,000 - 1,00,00,000 PA.                                1
Name: count, Length: 813, dtype: int64

In [25]:
jobs['salary'] == 'Not disclosed'

0         True
1         True
2         True
3         True
4         True
         ...
79142    False
79143     True
79144     True
79145    False
79146    False
Name: salary, Length: 79147, dtype: bool

In [27]:
jobs[jobs['salary'] != 'Not disclosed']

,job_id,job_role,company,experience,salary,location,rating,reviews,resposibilities,posted_on,job_link,company_link
19,6.012301e+10,.Net Fullstack Developer,Citiustech,3-8 Yrs,"7,00,000 - 17,00,000 PA.","Hybrid - Pune, Bangalore/Bengaluru, Mumbai (Al...",4.0,742 Reviews,"c#,.net core,javascript,Microservices,Angular,...",1 Day Ago,https://www.naukri.com/job-listings-net-fullst...,https://www.naukri.com/citiustech-jobs-careers...
21,5.012301e+10,Hexaware Technologies || Azure DataBricks_Pysp...,Hexaware Technologies,6-11 Yrs,"10,00,000 - 20,00,000 PA.","Pune, Chennai, Mumbai (All Areas)",3.7,3172 Reviews,"Pyspark,Azure Databricks,Python,Azure Data Lak...",2 Days Ago,https://www.naukri.com/job-listings-hexaware-t...,https://www.naukri.com/hexaware-technologies-j...
23,3.112220e+11,Deputy Manager- Marketing (Digital & B2B)-Indu...,Exide,2-7 Yrs,"4,00,000 - 9,00,000 PA. (Including Variable: 2...","Kolkata, Hyderabad/Secunderabad, Pune, Bangalo...",3.7,1441 Reviews,"Sales Automation,digital initiative,dms,Salesf...",7 Days Ago,https://www.naukri.com/job-listings-deputy-man...,https://www.naukri.com/exide-jobs-careers-414
24,2.712220e+11,Customer Service Associate,Tech Mahindra,0-2 Yrs,"2,50,000 - 3,50,000 PA.","Temp. WFH - Noida, Kolkata, New Delhi, Hyderab...",3.7,21440 Reviews,"Bengali,International BPO,BPO,Customer Service...",9 Days Ago,https://www.naukri.com/job-listings-customer-s...,https://www.naukri.com/tech-mahindra-jobs-care...
25,2.112220e+11,Senior Java BED ( PAN India)- KG,Tech Mahindra,8-12 Yrs,"25,00,000 - 27,50,000 PA.","Temp. WFH - Noida, Kolkata, Hyderabad/Secunder...",3.7,21440 Reviews,"Kafka,sql,spring boot,REST API,java,Lambda,Des...",2 Days Ago,https://www.naukri.com/job-listings-senior-jav...,https://www.naukri.com/born-commerce-jobs-care...
...,...,...,...,...,...,...,...,...,...,...,...,...
79125,2.712220e+11,Customer Service Associate,Tech Mahindra,0-2 Yrs,"2,50,000 - 3,50,000 PA.","Temp. WFH - Noida, Kolkata, New Delhi, Hyderab...",3.7,21440 Reviews,"Bengali,International BPO,BPO,Customer Service...",10 Days Ago,https://www.naukri.com/job-listings-customer-s...,https://www.naukri.com/tech-mahindra-jobs-care...
79126,2.112220e+11,Senior Java BED ( PAN India)- KG,Tech Mahindra,8-12 Yrs,"25,00,000 - 27,50,000 PA.","Temp. WFH - Noida, Kolkata, Hyderabad/Secunder...",3.7,21440 Reviews,"Kafka,sql,spring boot,REST API,java,Lambda,Des...",3 Days Ago,https://www.naukri.com/job-listings-senior-jav...,https://www.naukri.com/born-commerce-jobs-care...
79142,6.012301e+10,.Net Fullstack Developer,Citiustech,3-8 Yrs,"7,00,000 - 17,00,000 PA.","Hybrid - Pune, Bangalore/Bengaluru, Mumbai (Al...",4.0,742 Reviews,"c#,.net core,javascript,Microservices,Angular,...",2 Days Ago,https://www.naukri.com/job-listings-net-fullst...,https://www.naukri.com/citiustech-jobs-careers...
79145,2.712220e+11,Customer Service Associate,Tech Mahindra,0-2 Yrs,"2,50,000 - 3,50,000 PA.","Temp. WFH - Noida, Kolkata, New Delhi, Hyderab...",3.7,21440 Reviews,"Bengali,International BPO,BPO,Customer Service...",10 Days Ago,https://www.naukri.com/job-listings-customer-s...,https://www.naukri.com/tech-mahindra-jobs-care...
79146,2.112220e+11,Senior Java BED ( PAN India)- KG,Tech Mahindra,8-12 Yrs,"25,00,000 - 27,50,000 PA.","Temp. WFH - Noida, Kolkata, Hyderabad/Secunder...",3.7,21440 Reviews,"Kafka,sql,spring boot,REST API,java,Lambda,Des...",3 Days Ago,https://www.naukri.com/job-listings-senior-jav...,https://www.naukri.com/born-commerce-jobs-care...